-- phpMyAdmin SQL Dump
-- version 4.8.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 15, 2019 at 05:47 AM
-- Server version: 10.1.33-MariaDB
-- PHP Version: 7.2.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `job_aggregator`
--

-- --------------------------------------------------------

--
-- Table structure for table `job`
--

CREATE TABLE `job` (
  `id` int(11) NOT NULL,
  `title` text,
  `link` text,
  `salary` text,
  `location` text,
  `job_type` text,
  `job_category` text,
  `job_office` text,
  `job_minimal_description` text,
  `country` text,
  `job_time` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `job`
--

INSERT INTO `job` (`id`, `title`, `link`, `salary`, `location`, `job_type`, `job_category`, `job_office`, `job_minimal_description`, `country`, `job_time`) VALUES
(1, 'Data Officer', 'https://www.brightermonday.co.ke/job/data-officer-4802xe', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Tiny Totos Kenya Limited', 'We are currently looking for an data officer to support our data collection and synchronizatio process.', 'Kenya', '14h'),
(2, 'Junior Programmer', 'https://www.brightermonday.co.ke/job/junior-programmer-mp6ke9', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Career Directions Limited', 'Our client would like to recruit a Junior programmer to play a significant role in assisting firms in making tough decisions to meet up their short as well as long term objectives.', 'Kenya', '3d'),
(3, 'Project Implementation and Software Development Manager', 'https://www.brightermonday.co.ke/job/project-implementation-and-software-development-manager-x2gnvz', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Career Directions Limited', '10 years of experience in managing software projects both development and implementation, building teams and maintaining customer relations.', 'Kenya', '3d'),
(4, 'Software Developer Internship', 'https://www.brightermonday.co.ke/job/software-developer-internship-job-opening-zdzq5x', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'AfroData Technologies', 'We are looking for self-motivated individuals to engaged in all phases of the software development lifecycle which include: gathering and analyzing user/business system requirements, responding to outages and creating application system models. Participate in design meetings and consult with cli ...', 'Kenya', '5d'),
(5, 'Hotel IT Officer - Homabay (Must have 4*/5* hotel experience)', 'https://www.brightermonday.co.ke/job/hotel-ict-manager-homabay-must-have-45-hotel-experience-mp6knd', 'KSh Confidential', 'Rest of Kenya', 'Full Time', 'IT & Software', 'The African Talent Company | TATC', 'Our client is a high-end fast growing 4 star Hotel. They are looking to grow their team for the Hotel in Nairobi and Nyanza with top notch professionals for the role of IT Officer', 'Kenya', '5d'),
(6, 'Intern for Mobile development', 'https://www.brightermonday.co.ke/job/intern-for-mobile-development-2q72wv', 'KSh Confidential', 'Nairobi', 'Internships & Graduate', 'IT & Software', 'Hudutech Solutions', 'We are looking for a Mobile App Developer who possesses a passion for pushing mobile technologies to the limits. This developer will work with our team of talented engineers to design and build the next generation of our mobile applications.', 'Kenya', '5d'),
(7, 'IT Support Technician', 'https://www.brightermonday.co.ke/job/it-support-technician-x2gng0', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Gain Ventures Limited', 'IT support technicians provide assistance to computer users by answering questions, resolving technical problems and maintaining a company\'s network, software and computer equipment.', 'Kenya', '6d'),
(8, 'Website Development Manager', 'https://www.brightermonday.co.ke/job/website-development-manager-p6050w', 'KSh 15,001 - 30,000', 'Rest of Kenya', 'Full Time', 'IT & Software', 'Finahost Online Solutions', 'We are looking for an experienced website development manager for our enterprise. Our ideal candidate should be experienced with Wordpresss CMS & SEO.', 'Kenya', '6d'),
(9, 'Web and Mobile Developer', 'https://www.brightermonday.co.ke/job/web-and-mobile-developer-zdz579', 'KSh 30,001 - 45,000', 'Nairobi', 'Full Time', 'IT & Software', 'Mobile Pay Limited', 'Developer for Android studio, java, Javascript, CSS, MySQL, PHP, Bootstrap, Database driven APPs and Web-Applications (In Laravel)', 'Kenya', '1w'),
(10, 'Software Support Engineer', 'https://www.brightermonday.co.ke/job/software-support-engineer-q798k4', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Compulynx Ltd', 'A Software support specialist who will assist in the technical troubleshooting of systems.', 'Kenya', '1w'),
(11, 'Software Engineer', 'https://www.brightermonday.co.ke/job/software-engineer-dk0jjj', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Career Directions Limited', 'We are looking for the enthusiastic and result oriented candidate to fill in the position of Software engineer.', 'Kenya', '1w'),
(12, 'Senior Java Developer - IoT - Kenya', 'https://www.brightermonday.co.ke/job/senior-java-developer-iot-veg5gg', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'AltGen LTD', 'JAVA, JAVASCRIPT, HTML, CSS, SQL, GIT. Am I speaking your language? Then this new role might be the perfect opportunity that you have been waiting for', 'Kenya', '1w'),
(13, 'Full-Stack Web Developer', 'https://www.brightermonday.co.ke/job/full-stack-web-developer-5x98p5', 'KSh 30,001 - 45,000', 'Nairobi', 'Full Time', 'IT & Software', 'My Health Africa Group Limited', 'Junior Full-stack Web Developer working with Wordpress, APIs, PHP and other coding languages.', 'Kenya', '1w'),
(14, 'User Experience Researcher & Designer', 'https://www.brightermonday.co.ke/job/user-experience-researcher-designer-0wn07j', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Summit Recruitment & Search', 'Our client, the largest agricultural -commodity supply chain company in East & Southern Africa is launching a new digital platform vertical in Kenya. They are currently looking to recruit an experienced and creative UX Designer.', 'Kenya', '1w'),
(15, 'UI Designer', 'https://www.brightermonday.co.ke/job/ui-designer-veg5wj', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Summit Recruitment & Search', 'Our client, the largest agricultural -commodity supply chain company in East & Southern Africa is launching a new digital platform vertical in Kenya. They are currently looking to recruit an experienced and creative UI Designer.', 'Kenya', '1w'),
(16, 'Smart City System Architect', 'https://www.brightermonday.co.ke/job/smart-city-system-architect-995dp5', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Career Directions Limited', 'Overall architecture design, solution design, topic planning, and report writing of the Smart City project;', 'Kenya', '2w'),
(17, 'IT Officer', 'https://www.brightermonday.co.ke/job/it-officer-zdz6qg', 'KSh 30,001 - 45,000', 'Nairobi', 'Full Time', 'IT & Software', 'Summit Recruitment & Search', 'Our client, a leading Tours and Travel Company in Kenya is seeking to recruit an IT Officer. The ideal candidate must have a minimum of 2 years in IT Support.', 'Kenya', '2w'),
(18, 'Short Term Data Entry Assistant NTD Programs', 'https://www.brightermonday.co.tz/job/short-term-data-entry-assistant-ntd-programs-2q72x6', 'TSh Confidential', 'Dar es Salaam', 'Full Time', 'IT & Software', 'Helen Keller International', 'Country Overview: Established in 1984, the HKI-Tanzania office was the organization\'s first in Africa set up to provide primary eye care services in central Tanzania. HKI has since expanded its role and currently works in partnership with the Ministry of Health, Community Development, Gender, ...', 'Tanzania', '3d'),
(19, 'System Developer', 'https://www.brightermonday.co.tz/job/system-developer-zdz696', 'TSh Confidential', 'Dar es Salaam', 'Full Time', 'IT & Software', 'Coseke Tanzania limited', 'Our Company is looking for a System Developer who possesses a strong computer science fundamentals and solid experience with industry-standard technologies to join our elite team of product development professionals. We are looking for an innovative System Developer who will drive all aspects o ...', 'Tanzania', '2w'),
(20, 'IT Systems Administrator', 'https://www.brightermonday.co.tz/job/it-systems-administrator-2q75wd', 'TSh Confidential', 'Dar es Salaam', 'Full Time', 'IT & Software', 'AL MUNTAZIR SCHOOLS', 'We seek to hire a qualified candidate for the position of an IT Systems Administrator', 'Tanzania', '3w'),
(21, 'Solution (Technical) Architect', 'https://www.brightermonday.co.tz/job/solution-technical-architect-w2gwm6', 'TSh 1,500,001 - 2,000,000', 'Dar es Salaam', 'Full Time', 'IT & Software', 'Inventions Technologies Co. Ltd', 'Responsible for the technical analysis and holistic solution design of future capabilities and features, including external dependencies, cross-domain', 'Tanzania', '1mo'),
(22, 'Data Center Market Manager', 'https://www.brightermonday.co.ke/job/data-center-market-manager-eq9726', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Career Directions Limited', 'Be responsible for the development and sales of the data center business.', 'Kenya', '2w'),
(23, 'System Developer', 'https://www.brightermonday.co.tz/job/system-developer-rvnj28', 'TSh 500,001 - 1,000,000', 'Dar es Salaam', 'Full Time', 'IT & Software', 'Dudumizi Technologies LTD', 'System developer will be responsible in developing functional programs (Applications and Systems) that serve user needs.', 'Tanzania', '1mo'),
(24, 'System Architect', 'https://www.brightermonday.co.ke/job/system-architect-jrpw2g', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Career Directions Limited', 'Overall architecture design, solution design, topic planning, and report writing of the Smart City project;', 'Kenya', '2w'),
(25, 'Technical Staff', 'https://www.brightermonday.co.tz/job/technical-staff-nx704r', 'TSh Confidential', 'Dar es Salaam', 'Full Time', 'IT & Software', 'VIETTEL TANZANIA PLC', 'Halotel is always looking for individual who are Professionals, Talented and Passionate about telecommunication as we are, to join our Family in building the Fastest Growing Telecom in Tanzania.', 'Tanzania', '1mo'),
(26, 'Junior Security Consultant', 'https://www.brightermonday.co.ke/job/junior-security-consultant-vegqmx', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'SILENSEC', 'Silensec, a management consulting, technology services and training company specialized in information security, wants to hire fulltime Junior Security Consultants to join its leading team of consultants to serve its clients.', 'Kenya', '2w'),
(27, 'IT Staff', 'https://www.brightermonday.co.tz/job/it-staff-995rpp', 'TSh Confidential', 'Dar es Salaam', 'Full Time', 'IT & Software', 'VIETTEL TANZANIA PLC', 'Halotel is always looking for individual who are Professionals, Talented and Passionate about telecommunication as we are, to join our Family in building the Fastest Growing Telecom in Tanzania.', 'Tanzania', '1mo'),
(28, 'Junior Software Developer', 'https://www.brightermonday.co.ke/job/junior-software-developer-kgp24m', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Taz Technologies Ltd', 'As a Junior Software Developer you will work with a team of mid-level and senior engineers to develop, test, and maintain software applications and programs', 'Kenya', '3w'),
(29, 'Tech Support Officer', 'https://www.brightermonday.co.ke/job/tech-support-officer-480768', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', '4G Capital (4th Generation Capital)', 'This role purpose is to provide support to the business operations through ICT by providing standards, skills, experience & guidance in implementing the most efficient technology to achieve the company vision & mission.', 'Kenya', '3w'),
(30, 'Software Developer (Websites & Mobile Apps)', 'https://www.brightermonday.co.ke/job/mobile-apps-developer-and-uigraphic-designer-mp6dpw', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Ingressive Emotion', 'You will be developing mobile apps and web applications to support the company\'s core products and internal systems.', 'Kenya', '3w'),
(31, 'Backend Software Engineer', 'https://www.brightermonday.co.ke/job/backend-software-engineer-p602px', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Corporate Staffing Services Ltd', 'Our client is a modern and fast growing online ride hailing company based in the Middle East and Africa aimed at providing an on demand taxi service across major cities and towns.', 'Kenya', '3w'),
(32, 'Android Software Engineer', 'https://www.brightermonday.co.ke/job/android-software-engineer-jrp2m8', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Corporate Staffing Services Ltd', 'Our client is a modern and fast growing online ride hailing company based in the Middle East and Africa aimed at providing an on demand taxi service across major cities and towns.', 'Kenya', '3w'),
(33, 'IOS Software Engineer', 'https://www.brightermonday.co.ke/job/ios-software-engineer-g9pz5e', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Corporate Staffing Services Ltd', 'Our client is a modern and fast-growing online ride-hailing company based in the Middle East and Africa aimed at providing an on-demand taxi service across major cities and towns.', 'Kenya', '3w'),
(34, 'Head of IT Operations and Systems Development', 'https://www.brightermonday.co.ke/job/head-of-it-operations-and-systems-development-g9p86r', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Sudi Resources Holdings Limited', 'The Head of IT and Systems Development will be responsible for the Coordination of the IT related tasks within the company which includes the continuous development and Maintenance of the gaming platform and any other Products to be introduced by the company.', 'Kenya', '4w'),
(35, 'Back End Developer @ ICTLife', 'https://www.brightermonday.co.ke/job/back-end-developer-at-ictlife-6kn5z4', 'KSh 150,001 - 200,000', 'Nairobi', 'Full Time', 'IT & Software', 'Ideas Come To Life', 'Back End Developer Position at Ideas Come To Life - Preferred Golang & React', 'Kenya', '1mo'),
(36, 'Trainee IOS Developer', 'https://www.brightermonday.co.ke/job/trainee-ios-developer-995nq8', 'KSh 0 - 15,000', 'Nairobi', 'Full Time', 'IT & Software', 'i Manage Limited', 'You will participate in developing applications for mobile devices powered by Apple\'s iOS operating system.', 'Kenya', '1mo'),
(37, 'Software Engineer (Front End)', 'https://www.brightermonday.co.ke/job/software-engineer-front-end-2q7w52', 'KSh 105,001 - 150,000', 'Nairobi', 'Full Time', 'IT & Software', 'Treen Creations Ltd', 'Write maintainable code and build stable features using our modern technology stack.', 'Kenya', '1mo'),
(38, 'Mobile & Web software developer', 'https://www.brightermonday.co.ke/job/mobile-web-software-developer-6knvkn', 'KSh Confidential', 'Nairobi', 'Full Time', 'IT & Software', 'Afrinet Telecom Limited', 'Develop and implement new software programs by fully understanding of JAVA, JavaScript, PHP, ANDROID, and their environments.', 'Kenya', '1mo'),
(39, 'IT Personal', 'https://www.brightermonday.co.ug/job/it-personal-480qe5', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'The African Talent Company | TATC', 'Designing and programming system-level software: operating systems, database systems, embedded systems and so on.', 'Uganda', '1w'),
(40, 'Information Technology I.T. Admin', 'https://www.brightermonday.co.ug/job/information-technology-it-admin-eq92zk', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Anonymous Employer', 'The qualified the candidate will mainly help in managing the business', 'Uganda', '3w'),
(41, 'Full Stack Developer', 'https://www.brightermonday.co.ug/job/full-stack-developer-75p9wj', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Tenbagsfull', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '3w'),
(42, 'Management Information Systems Officer', 'https://www.brightermonday.co.ug/job/management-information-systems-officer-zdzqxn', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'ECLOF- Uganda', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '5d'),
(43, 'ICT Manager', 'https://www.brightermonday.co.ug/job/ict-manager-w2g9mz', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Uganda Clays Limited', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1w'),
(44, 'Health Information Assistant', 'https://www.brightermonday.co.ug/job/health-information-assistant-5x98g6', 'USh Confidential', 'Rest of Uganda', 'Full Time', 'IT & Software', 'Wakiso District Local Government', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1w'),
(45, 'Information Technology Officer', 'https://www.brightermonday.co.ug/job/information-technology-officer-75prjq', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Pakwach District Local Government', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1w'),
(46, 'Data clerks', 'https://www.brightermonday.co.ug/job/data-clerks-480mwp', 'USh Confidential', 'Outside Uganda', 'Full Time', 'IT & Software', 'Child And Family Foundation Uganda (CFU)', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '2w'),
(47, 'National Radiologic Technology Officer', 'https://www.brightermonday.co.ug/job/national-radiologic-technology-officer-995dwj', 'USh Confidential', 'Outside Uganda', 'Full Time', 'IT & Software', 'International Organization for Migration', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '2w'),
(48, 'Senior Information Management Officer', 'https://www.brightermonday.co.ug/job/senior-information-management-officer-6knmz7', 'USh Confidential', 'Outside Uganda', 'Full Time', 'IT & Software', 'Medair', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '2w'),
(49, 'Resource Transfer Manager', 'https://www.brightermonday.co.ug/job/resource-transfer-manager-6knm5z', 'USh Confidential', 'Outside Uganda', 'Full Time', 'IT & Software', 'Catholic Relief Services', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '2w'),
(50, 'Chief Technology Officer', 'https://www.brightermonday.co.ug/job/chief-technology-officer-5x9vep', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Fenix International', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '3w'),
(51, 'IT Manager', 'https://www.brightermonday.co.ug/job/it-manager-0wn5jm', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'SGA Security Group Uganda Limited', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '3w'),
(52, 'Product Owner – Mobile App', 'https://www.brightermonday.co.ug/job/product-owner-mobile-app-5x9znp', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'SafeBoda', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1mo'),
(53, 'Recency Data Manager', 'https://www.brightermonday.co.ug/job/recency-data-manager-dk0dxj', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Global Programs for Research and Training (GP)', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1mo'),
(54, 'IT Specialist/Supervisor', 'https://www.brightermonday.co.ug/job/it-specialistsupervisor-995rpn', 'USh 800,001 - 900,000', 'Kampala', 'Full Time', 'IT & Software', 'Anonymous Employer', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1mo'),
(55, 'IT Personal', 'https://www.brightermonday.co.ug/job/it-personal-480qe5', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'The African Talent Company | TATC', 'Designing and programming system-level software: operating systems, database systems, embedded systems and so on.', 'Uganda', '1w'),
(56, 'Information Technology I.T. Admin', 'https://www.brightermonday.co.ug/job/information-technology-it-admin-eq92zk', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Anonymous Employer', 'The qualified the candidate will mainly help in managing the business', 'Uganda', '3w'),
(57, 'Full Stack Developer', 'https://www.brightermonday.co.ug/job/full-stack-developer-75p9wj', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Tenbagsfull', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '3w'),
(58, 'Management Information Systems Officer', 'https://www.brightermonday.co.ug/job/management-information-systems-officer-zdzqxn', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'ECLOF- Uganda', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '5d'),
(59, 'ICT Manager', 'https://www.brightermonday.co.ug/job/ict-manager-w2g9mz', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Uganda Clays Limited', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1w'),
(60, 'Health Information Assistant', 'https://www.brightermonday.co.ug/job/health-information-assistant-5x98g6', 'USh Confidential', 'Rest of Uganda', 'Full Time', 'IT & Software', 'Wakiso District Local Government', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1w'),
(61, 'Information Technology Officer', 'https://www.brightermonday.co.ug/job/information-technology-officer-75prjq', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Pakwach District Local Government', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1w'),
(62, 'Data clerks', 'https://www.brightermonday.co.ug/job/data-clerks-480mwp', 'USh Confidential', 'Outside Uganda', 'Full Time', 'IT & Software', 'Child And Family Foundation Uganda (CFU)', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '2w'),
(63, 'National Radiologic Technology Officer', 'https://www.brightermonday.co.ug/job/national-radiologic-technology-officer-995dwj', 'USh Confidential', 'Outside Uganda', 'Full Time', 'IT & Software', 'International Organization for Migration', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '2w'),
(64, 'Senior Information Management Officer', 'https://www.brightermonday.co.ug/job/senior-information-management-officer-6knmz7', 'USh Confidential', 'Outside Uganda', 'Full Time', 'IT & Software', 'Medair', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '2w'),
(65, 'Resource Transfer Manager', 'https://www.brightermonday.co.ug/job/resource-transfer-manager-6knm5z', 'USh Confidential', 'Outside Uganda', 'Full Time', 'IT & Software', 'Catholic Relief Services', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '2w'),
(66, 'Chief Technology Officer', 'https://www.brightermonday.co.ug/job/chief-technology-officer-5x9vep', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Fenix International', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '3w'),
(67, 'IT Manager', 'https://www.brightermonday.co.ug/job/it-manager-0wn5jm', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'SGA Security Group Uganda Limited', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '3w'),
(68, 'Product Owner – Mobile App', 'https://www.brightermonday.co.ug/job/product-owner-mobile-app-5x9znp', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'SafeBoda', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1mo'),
(69, 'Recency Data Manager', 'https://www.brightermonday.co.ug/job/recency-data-manager-dk0dxj', 'USh Confidential', 'Kampala', 'Full Time', 'IT & Software', 'Global Programs for Research and Training (GP)', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1mo'),
(70, 'IT Specialist/Supervisor', 'https://www.brightermonday.co.ug/job/it-specialistsupervisor-995rpn', 'USh 800,001 - 900,000', 'Kampala', 'Full Time', 'IT & Software', 'Anonymous Employer', 'We are currently looking for Full-stack .NET/ React Developers to join our Company and be an integral part of our team. Our Full Stack developer must have knowledge in all stages of software development.', 'Uganda', '1mo');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `job`
--
ALTER TABLE `job`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `job`
--
ALTER TABLE `job`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=71;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
